# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# copy manifests and install
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
COPY scripts ./scripts

RUN npm install --ignore-scripts
RUN npm run build

CMD ["npx","-y","@modelcontextprotocol/server-everything"]
